/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LopController;
import controller.PhieuMuonController;
import controller.SachController;
import controller.SinhVienController;
import controller.theLoaiSachController;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PhieuMuon;
import model.Sach;
import model.SinhVien;
import model.TheLoaiSach;

/**
 *
 * @author OS
 */
public class ThongKe extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
        loadSinhVien();
        loadsach();
        loadTheLoaiSach();
        loadPhieuMuon();
        loadcbboxTheLoai();
        loadcbboxTheLoaiTang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void loadSinhVien() {
        tblSV.setModel(new DefaultTableModel(null, new String[]{"Mã SV", "Mật Khẩu", "Lớp", "Họ Tên", "Ngày Sinh", "Giới Tính", "Địa Chỉ", "SDT", "Email"}));
        ArrayList<SinhVien> list = new SinhVienController().danhSachTatCaSinhVien();
        DefaultTableModel model = (DefaultTableModel) tblSV.getModel();
        Object rowData[] = new Object[9];
        LopController lopController = new LopController();
        for (SinhVien item : list) {
            rowData[0] = item.getMaSv();
            rowData[1] = item.getPassword();
            rowData[2] = lopController.layTenTheoMaLop(item.getMaLop());

            rowData[3] = item.getHoTen();
            rowData[4] = item.getNgaySinh();
            if (item.getGioiTinh()) {
                rowData[5] = "Nam";
            } else {
                rowData[5] = "Nữ";
            }
            rowData[6] = item.getDiaChi();
            rowData[7] = item.getSoDienThoai();
            rowData[8] = item.getEmail();
            model.addRow(rowData);
        }

    }

    private void loadsach() {
        tblSach.setModel(new DefaultTableModel(null, new String[]{"Mã Sách", "Tên Sách", "Mã Thể Loại", "Tác Giả", "Số Lượng", "Mã Nhà Xuất Bản", "Ngày Xuất Bản", "Nội Dung"}));
        ArrayList<Sach> list = new SachController().danhSachTatCaSach();
        DefaultTableModel model = (DefaultTableModel) tblSach.getModel();

        Object rowData[] = new Object[8];
        for (Sach item : list) {
            rowData[0] = item.getMaSach();
            rowData[1] = item.getTenSach();
            rowData[2] = item.getMaTheLoai();
            rowData[3] = item.getTacGia();
            rowData[4] = item.getSoLuong();
            rowData[5] = item.getMaNXB();
            rowData[6] = item.getNgay();
            rowData[7] = item.getNoiDung();
            model.addRow(rowData);
        }

    }
 public void loadTheLoaiSach(){
         tblTLS.setModel(new DefaultTableModel(null,new String[]{"Mã Thể Loại","Tên Thể Loại","Vị Trí"}));
        theLoaiSachController controller = new theLoaiSachController();
        ArrayList<TheLoaiSach> list = controller.ListTheLoai();
        DefaultTableModel model = (DefaultTableModel) tblTLS.getModel();
       
        Object rowData[] = new Object[3];
        for(TheLoaiSach item : list){
            rowData[0] = item.getMaTheLoai();
            rowData[1] = item.getTenTheLoai();
            rowData[2] = item.getViTri();
            model.addRow(rowData);
        }
    }
     public void loadPhieuMuon(){
       try {
              tblPM.setModel(new DefaultTableModel(null,new String[]{"Mã Phiếu Mượn","Mã Sinh Viên","Mã Sách","Số Lượng","Ngày Mượn","Ngày Hẹn Trả"}));
        PhieuMuonController controller = new PhieuMuonController();
        ArrayList<PhieuMuon> list = controller.listPhieuMuon();
        DefaultTableModel model = (DefaultTableModel) tblPM.getModel();
       
        Object rowData[] = new Object[6];
        for(PhieuMuon item : list){
            rowData[0] = item.getMaPhieuMuon();
            rowData[1] = item.getMaSinhVien();
            rowData[2] = item.getMaSach();
            rowData[3] = item.getSoLuong();
            rowData[4] = item.getNgayMuon();
            rowData[5] = item.getNgayHetHan();
            model.addRow(rowData);
    }
    }catch (Exception e){
            System.out.println("ERrOR " + e);
            }
       }
     
     public void LoadGioiTinh(int search){
        SinhVienController svc = new SinhVienController();
        ArrayList<SinhVien> ds = svc.SearchSvTheoGioiTinh(search);
//        DefaultTableModel dtm = (DefaultTableModel)tblSV.getModel();
//        dtm.setRowCount(0);//xóa các dòng cũ nếu có
            
        tblSV.setModel(new DefaultTableModel(null, new String[]{"Mã Sách", "Tên Sách", "Mã Thể Loại", "Tác Giả", "Số Lượng", "Mã Nhà Xuất Bản", "Ngày Xuất Bản", "Nội Dung"}));
        DefaultTableModel model = (DefaultTableModel) tblSV.getModel();
        LopController lopController = new LopController();
        Object rowData[] = new Object[9];
        for (SinhVien item : ds) {
            rowData[0] = item.getMaSv();
            rowData[1] = item.getPassword();
            rowData[2] = lopController.layTenTheoMaLop(item.getMaLop());
            rowData[3] = item.getHoTen();
            rowData[4] = item.getNgaySinh();
            if (item.getGioiTinh()) {
                rowData[5] = "Nam";
            } else {
                rowData[5] = "Nữ";
            }
            rowData[6] = item.getDiaChi();
            rowData[7] = item.getSoDienThoai();
            rowData[8] = item.getEmail();
            model.addRow(rowData);
        }
     }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblsoGioiTinhSV = new javax.swing.JLabel();
        cboGioiTinhSV = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSV = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblTongSachS = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        txtSearch1 = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JLabel();
        cboSachPM1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTLS = new javax.swing.JTable();
        lblsoSachTLS = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboTenTLS = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cboViTriTLS = new javax.swing.JComboBox();
        lblsoTheLoaiTLS = new javax.swing.JLabel();
        txtSearch2 = new javax.swing.JTextField();
        btnSearch2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        cboSachPM = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPM = new javax.swing.JTable();
        txtSearch3 = new javax.swing.JTextField();
        btnSearch3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(37, 41, 49));
        jPanel4.setMaximumSize(new java.awt.Dimension(1600, 754));
        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(1154, 754));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Thống Kê");

        jTabbedPane1.setBackground(new java.awt.Color(197, 197, 197));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1154, 700));

        jPanel1.setBackground(new java.awt.Color(37, 41, 49));

        jPanel5.setBackground(new java.awt.Color(37, 41, 49));
        jPanel5.setMinimumSize(new java.awt.Dimension(1154, 650));
        jPanel5.setPreferredSize(new java.awt.Dimension(1154, 754));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Giới tính: ");

        lblsoGioiTinhSV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblsoGioiTinhSV.setForeground(new java.awt.Color(240, 240, 240));
        lblsoGioiTinhSV.setText("Tổng số Sinh Viên: ");

        cboGioiTinhSV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cboGioiTinhSV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Nam", "Nữ" }));
        cboGioiTinhSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGioiTinhSVActionPerformed(evt);
            }
        });

        tblSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SV", "Password", "Họ và tên", "Ngày Sinh", "Giới tính", "Địa chỉ", "Sđt", "Email"
            }
        ));
        tblSV.setRowHeight(30);
        jScrollPane1.setViewportView(tblSV);

        btnSearch.setForeground(new java.awt.Color(51, 255, 102));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblsoGioiTinhSV))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cboGioiTinhSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch)))))
                .addGap(0, 187, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboGioiTinhSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addComponent(lblsoGioiTinhSV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sinh Viên", jPanel1);

        jPanel2.setBackground(new java.awt.Color(37, 41, 49));

        jPanel6.setBackground(new java.awt.Color(37, 41, 49));

        lblTongSachS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTongSachS.setForeground(new java.awt.Color(240, 240, 240));

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Mã Thể Loại", "Tác Giả", "Số lượng", "NXB", "Ngày nhập", "NDTT", "Hình"
            }
        ));
        tblSach.setRowHeight(30);
        jScrollPane2.setViewportView(tblSach);

        btnSearch1.setForeground(new java.awt.Color(51, 255, 102));
        btnSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearch1MouseClicked(evt);
            }
        });

        cboSachPM1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cboSachPM1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Tăng Dần ", "Giảm Dần", " " }));
        cboSachPM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSachPM1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Số lượng sách");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblTongSachS, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel15)
                        .addGap(30, 30, 30)
                        .addComponent(cboSachPM1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch1)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboSachPM1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTongSachS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sách", jPanel2);

        jPanel3.setBackground(new java.awt.Color(37, 41, 49));

        jPanel7.setBackground(new java.awt.Color(37, 41, 49));
        jPanel7.setPreferredSize(new java.awt.Dimension(1000, 412));

        tblTLS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Thể Loại", "Tên Thể Loại", "Vị trí", "Mã Sách", "Tên Sách", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTLS.setRowHeight(30);
        jScrollPane3.setViewportView(tblTLS);

        lblsoSachTLS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblsoSachTLS.setForeground(new java.awt.Color(240, 240, 240));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Thể loại");

        cboTenTLS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cboTenTLS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả" }));
        cboTenTLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboTenTLSMouseClicked(evt);
            }
        });
        cboTenTLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenTLSActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Vị trí");

        cboViTriTLS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cboViTriTLS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả" }));
        cboViTriTLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboViTriTLSActionPerformed(evt);
            }
        });

        lblsoTheLoaiTLS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblsoTheLoaiTLS.setForeground(new java.awt.Color(240, 240, 240));

        btnSearch2.setForeground(new java.awt.Color(51, 255, 102));
        btnSearch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnSearch2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearch2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblsoTheLoaiTLS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(lblsoSachTLS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(138, 138, 138))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(31, 31, 31)
                                .addComponent(cboTenTLS, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(35, 35, 35)))
                        .addComponent(cboViTriTLS, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboTenTLS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboViTriTLS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsoSachTLS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblsoTheLoaiTLS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thể Loại Sách", jPanel3);

        jPanel9.setBackground(new java.awt.Color(37, 41, 49));

        cboSachPM.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cboSachPM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Tăng Dần ", "Giảm Dần", " " }));
        cboSachPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSachPMActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Số lượng sách");

        jPanel10.setBackground(new java.awt.Color(197, 197, 197));
        jPanel10.setPreferredSize(new java.awt.Dimension(550, 100));
        jPanel10.setLayout(new java.awt.CardLayout());

        jPanel12.setBackground(new java.awt.Color(197, 197, 197));

        jPanel11.setBackground(new java.awt.Color(197, 197, 197));

        tblPM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã PM", "Mã SV", "Tên SV", "Mã Sách", "Tên Sách", "Số lượng", "Ngày Mượn", "Ngày Hẹn Trả"
            }
        ));
        tblPM.setRowHeight(30);
        jScrollPane5.setViewportView(tblPM);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel12, "card3");

        btnSearch3.setForeground(new java.awt.Color(51, 255, 102));
        btnSearch3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnSearch3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearch3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboSachPM, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(398, 398, 398)
                        .addComponent(txtSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch3))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboSachPM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jTabbedPane1.addTab("Phiếu Mượn", jPanel9);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(100, 100, 100)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1180, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboGioiTinhSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGioiTinhSVActionPerformed

        String GioiTinh = (String)cboGioiTinhSV.getSelectedItem();
//        System.out.println(GioiTinh);
        int search=0;
        if(GioiTinh == "Nam"){
            search =1;
            LoadGioiTinh(search);
        }
        else if (GioiTinh == "Nữ"){
            search = 0;
            LoadGioiTinh(search);
        }
        else{
            loadSinhVien();
        }
        
        
        
    }//GEN-LAST:event_cboGioiTinhSVActionPerformed

    public void loadSinhVienTimTheoTen() {
        SinhVienController svc = new SinhVienController();
        ArrayList<SinhVien> listsv = svc.SearchSvTheoTen(txtSearch.getText());
        DefaultTableModel model = (DefaultTableModel) tblSV.getModel();
        model.setRowCount(0);
        LopController lopController = new LopController();
        ArrayList<SinhVien> listsvTheoMa = svc.SearchSvTheoMa(txtSearch.getText());
        for (SinhVien sinhVien : listsvTheoMa) {
            listsv.add(sinhVien);
        }
        for (SinhVien sv : listsv) {
            String tenLop = lopController.layTenTheoMaLop(sv.getMaLop());
            Object[] row = new Object[]{
                sv.getMaSv(),
                sv.getPassword(),
                tenLop,
                sv.getHoTen(),
                sv.getNgaySinh(),
                sv.getGioiTinh(),
                sv.getDiaChi(),
                sv.getSoDienThoai(),
                sv.getEmail()
            };
            model.addRow(row);
        }
    }
    
    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        loadSinhVienTimTheoTen();
    }//GEN-LAST:event_btnSearchMouseClicked

    public void loadSearchSach() {
        SachController scl = new SachController();
        ArrayList<Sach> lists = new ArrayList<>();

        DefaultTableModel model = (DefaultTableModel) tblSach.getModel();
        model.setRowCount(0);
        ArrayList<Sach> listsTheoMa = scl.SearchTen(txtSearch1.getText());
        for (Sach sach : listsTheoMa) {
            lists.add(sach);
        }
        theLoaiSachController tlsc = new theLoaiSachController();
        for (Sach s : lists) {
            Object[] row = new Object[]{
                s.getMaSach(),
                s.getTenSach(),
                tlsc.layTenTheoMa(s.getMaTheLoai()),
                s.getTacGia(),
                s.getSoLuong(),
                s.getMaNXB(),
                s.getNgay(),
                s.getNoiDung()              
            };
            model.addRow(row);
        }
    }
    
    private void btnSearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch1MouseClicked
        // TODO add your handling code here:
        loadSearchSach();
    }//GEN-LAST:event_btnSearch1MouseClicked

    public void loadSearchtl() {
        theLoaiSachController scl = new theLoaiSachController();
        ArrayList<TheLoaiSach> lists = new ArrayList<>();

        DefaultTableModel model = (DefaultTableModel) tblTLS.getModel();
        model.setRowCount(0);
        ArrayList<TheLoaiSach> listsTheoMa = scl.Search(txtSearch2.getText());
        for (TheLoaiSach tls : listsTheoMa) {
            lists.add(tls);
        }
        theLoaiSachController tlsc = new theLoaiSachController();
        for (TheLoaiSach s : lists) {
            Object[] row = new Object[]{
                s.getMaTheLoai(),
                s.getTenTheLoai(),
                s.getViTri()  
            };
            model.addRow(row);
        }
    }
    
    private void btnSearch2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch2MouseClicked
        // TODO add your handling code here:
        loadSearchtl();
    }//GEN-LAST:event_btnSearch2MouseClicked

    private void cboTenTLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTenTLSMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboTenTLSMouseClicked

    private void cboTenTLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenTLSActionPerformed
        // TODO add your handling code here:
        int vt = cboTenTLS.getSelectedIndex();
        if(vt == 0){
            loadTheLoaiSach();
           
        }else{
            String theloai = cboTenTLS.getSelectedItem().toString();
            theLoaiSachController scl = new theLoaiSachController();
            ArrayList<TheLoaiSach> lists = new ArrayList<>();

            DefaultTableModel model = (DefaultTableModel) tblTLS.getModel();
            model.setRowCount(0);
            ArrayList<TheLoaiSach> listsTheoMa = scl.Search(theloai);
            for (TheLoaiSach tls : listsTheoMa) {
                lists.add(tls);
            }
            theLoaiSachController tlsc = new theLoaiSachController();
            for (TheLoaiSach s : lists) {
                Object[] row = new Object[]{
                    s.getMaTheLoai(),
                    s.getTenTheLoai(),
                    s.getViTri()  
                };
                model.addRow(row);
            }
        }
        
    }//GEN-LAST:event_cboTenTLSActionPerformed

    private void cboViTriTLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboViTriTLSActionPerformed
        // TODO add your handling code here:
        if(cboViTriTLS.getSelectedIndex() == 0){
            loadTheLoaiSach();   
        }
        else{
                String theloai = cboViTriTLS.getSelectedItem().toString();
            theLoaiSachController scl = new theLoaiSachController();
            ArrayList<TheLoaiSach> lists = new ArrayList<>();

            DefaultTableModel model = (DefaultTableModel) tblTLS.getModel();
            model.setRowCount(0);
            ArrayList<TheLoaiSach> listsTheoMa = scl.Search(theloai);
            for (TheLoaiSach tls : listsTheoMa) {
                lists.add(tls);
            }
            theLoaiSachController tlsc = new theLoaiSachController();
            for (TheLoaiSach s : lists) {
                Object[] row = new Object[]{
                    s.getMaTheLoai(),
                    s.getTenTheLoai(),
                    s.getViTri()  
                };
                model.addRow(row);
            }
        }
        
    }//GEN-LAST:event_cboViTriTLSActionPerformed

    private void cboSachPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSachPMActionPerformed
        // TODO add your handling code here:
        if(cboSachPM.getSelectedIndex() == 0) {
            loadPhieuMuon();
        }
        else if(cboSachPM.getSelectedIndex() == 1){
            try {
            tblPM.setModel(new DefaultTableModel(null,new String[]{"Mã Phiếu Mượn","Mã Sinh Viên","Mã Sách","Số Lượng","Ngày Mượn","Ngày Hẹn Trả"}));
            PhieuMuonController controller = new PhieuMuonController();
            ArrayList<PhieuMuon> list = controller.PhieuMuonTangDan();
            DefaultTableModel model = (DefaultTableModel) tblPM.getModel();

            Object rowData[] = new Object[6];
            for(PhieuMuon item : list){
                rowData[0] = item.getMaPhieuMuon();
                rowData[1] = item.getMaSinhVien();
                rowData[2] = item.getMaSach();
                rowData[3] = item.getSoLuong();
                rowData[4] = item.getNgayMuon();
                rowData[5] = item.getNgayHetHan();
                model.addRow(rowData);
        }
        }catch (Exception e){
                System.out.println("ERrOR " + e);
                }
           }
        else{
            try {
            tblPM.setModel(new DefaultTableModel(null,new String[]{"Mã Phiếu Mượn","Mã Sinh Viên","Mã Sách","Số Lượng","Ngày Mượn","Ngày Hẹn Trả"}));
            PhieuMuonController controller = new PhieuMuonController();
            ArrayList<PhieuMuon> list = controller.PhieuMuonGiamDan();
            DefaultTableModel model = (DefaultTableModel) tblPM.getModel();

            Object rowData[] = new Object[6];
            for(PhieuMuon item : list){
                rowData[0] = item.getMaPhieuMuon();
                rowData[1] = item.getMaSinhVien();
                rowData[2] = item.getMaSach();
                rowData[3] = item.getSoLuong();
                rowData[4] = item.getNgayMuon();
                rowData[5] = item.getNgayHetHan();
                model.addRow(rowData);
            }
            }catch (Exception e){
                System.out.println("ERrOR " + e);
                }
        }

    }//GEN-LAST:event_cboSachPMActionPerformed

    public void searchPhieuMuon(){
//        ArrayList<PhieuMuon> listpm = new ArrayList<>();
        PhieuMuonController pmc = new PhieuMuonController();
        DefaultTableModel model = (DefaultTableModel) tblPM.getModel();
        model.setRowCount(0);
//        LopController lopController = new LopController();
        ArrayList<PhieuMuon> listsvTheoMa = pmc.SearchMaSVMaPhieu(txtSearch3.getText());
        for (PhieuMuon pm : listsvTheoMa) {
//            String tenLop = pmc.layTenTheoMaLop(sv.getMaLop());
                Object[] row = new Object[]{
                pm.getMaPhieuMuon(),
                pm.getMaSinhVien(),
                pm.getMaSach(),
                pm.getSoLuong(),
                pm.getNgayMuon(),
                pm.getNgayHetHan(),
            };
            model.addRow(row);
        }
    }
    
    private void btnSearch3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch3MouseClicked
        // TODO add your handling code here:
        searchPhieuMuon();
        
    }//GEN-LAST:event_btnSearch3MouseClicked

    private void cboSachPM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSachPM1ActionPerformed
        // TODO add your handling code here:
        if(cboSachPM1.getSelectedIndex() == 0){
            loadsach();
        }
        else if(cboSachPM1.getSelectedIndex() == 1){
            tblSach.setModel(new DefaultTableModel(null, new String[]{"Mã Sách", "Tên Sách", "Mã Thể Loại", "Tác Giả", "Số Lượng", "Mã Nhà Xuất Bản", "Ngày Xuất Bản", "Nội Dung"}));
            ArrayList<Sach> list = new SachController().danhsachTangDan();
            DefaultTableModel model = (DefaultTableModel) tblSach.getModel();

            Object rowData[] = new Object[8];
            for (Sach item : list) {
                rowData[0] = item.getMaSach();
                rowData[1] = item.getTenSach();
                rowData[2] = item.getMaTheLoai();
                rowData[3] = item.getTacGia();
                rowData[4] = item.getSoLuong();
                rowData[5] = item.getMaNXB();
                rowData[6] = item.getNgay();
                rowData[7] = item.getNoiDung();
                model.addRow(rowData);
            }
        }
        else{
            tblSach.setModel(new DefaultTableModel(null, new String[]{"Mã Sách", "Tên Sách", "Mã Thể Loại", "Tác Giả", "Số Lượng", "Mã Nhà Xuất Bản", "Ngày Xuất Bản", "Nội Dung"}));
            ArrayList<Sach> list = new SachController().danhSachGiamDan();
            DefaultTableModel model = (DefaultTableModel) tblSach.getModel();

            Object rowData[] = new Object[8];
            for (Sach item : list) {
                rowData[0] = item.getMaSach();
                rowData[1] = item.getTenSach();
                rowData[2] = item.getMaTheLoai();
                rowData[3] = item.getTacGia();
                rowData[4] = item.getSoLuong();
                rowData[5] = item.getMaNXB();
                rowData[6] = item.getNgay();
                rowData[7] = item.getNoiDung();
                model.addRow(rowData);
            }
        }
    }//GEN-LAST:event_cboSachPM1ActionPerformed

    public void loadcbboxTheLoai(){
    
//        sv.setMaLop(lopController.layMaLopTheoTen(comboBoxQlSinhVien.getSelectedItem().toString()));
        try {
            String sql = "Select * from theloaisach";

            Connection conn = util.ConnectDB.connectSQLServer();
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            TheLoaiSach lopController = new TheLoaiSach();
            while (rs.next()) {
                cboTenTLS.addItem(rs.getString(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    public void loadcbboxTheLoaiTang(){
    
//        sv.setMaLop(lopController.layMaLopTheoTen(comboBoxQlSinhVien.getSelectedItem().toString()));
        try {
            String sql = "Select * from theloaisach";

            Connection conn = util.ConnectDB.connectSQLServer();
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            TheLoaiSach lopController = new TheLoaiSach();
            while (rs.next()) {
                cboViTriTLS.addItem(rs.getString(3));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnSearch1;
    private javax.swing.JLabel btnSearch2;
    private javax.swing.JLabel btnSearch3;
    private javax.swing.JComboBox cboGioiTinhSV;
    private javax.swing.JComboBox cboSachPM;
    private javax.swing.JComboBox cboSachPM1;
    private javax.swing.JComboBox cboTenTLS;
    private javax.swing.JComboBox cboViTriTLS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblTongSachS;
    private javax.swing.JLabel lblsoGioiTinhSV;
    private javax.swing.JLabel lblsoSachTLS;
    private javax.swing.JLabel lblsoTheLoaiTLS;
    private javax.swing.JTable tblPM;
    private javax.swing.JTable tblSV;
    private javax.swing.JTable tblSach;
    private javax.swing.JTable tblTLS;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtSearch2;
    private javax.swing.JTextField txtSearch3;
    // End of variables declaration//GEN-END:variables
}
